---
abstract: 'Ohloh API implementation (DEPRECATED)'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Exception::Class: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Ohloh-API
provides:
  WWW::Ohloh::API:
    file: lib/WWW/Ohloh/API.pm
    version: v1.0.2
  WWW::Ohloh::API::Account:
    file: lib/WWW/Ohloh/API/Account.pm
    version: v1.0.2
  WWW::Ohloh::API::ActivityFact:
    file: lib/WWW/Ohloh/API/ActivityFact.pm
    version: v1.0.2
  WWW::Ohloh::API::ActivityFacts:
    file: lib/WWW/Ohloh/API/ActivityFacts.pm
    version: v1.0.2
  WWW::Ohloh::API::Analysis:
    file: lib/WWW/Ohloh/API/Analysis.pm
    version: v1.0.2
  WWW::Ohloh::API::Collection:
    file: lib/WWW/Ohloh/API/Collection.pm
    version: v1.0.2
  WWW::Ohloh::API::ContributorFact:
    file: lib/WWW/Ohloh/API/ContributorFact.pm
    version: v1.0.2
  WWW::Ohloh::API::ContributorLanguageFact:
    file: lib/WWW/Ohloh/API/ContributorLanguageFact.pm
    version: v1.0.2
  WWW::Ohloh::API::Enlistment:
    file: lib/WWW/Ohloh/API/Enlistment.pm
    version: v1.0.2
  WWW::Ohloh::API::Enlistments:
    file: lib/WWW/Ohloh/API/Enlistments.pm
    version: v1.0.2
  WWW::Ohloh::API::Factoid:
    file: lib/WWW/Ohloh/API/Factoid.pm
    version: v1.0.2
  WWW::Ohloh::API::Kudo:
    file: lib/WWW/Ohloh/API/Kudo.pm
    version: v1.0.2
  WWW::Ohloh::API::KudoScore:
    file: lib/WWW/Ohloh/API/KudoScore.pm
    version: v1.0.2
  WWW::Ohloh::API::Kudos:
    file: lib/WWW/Ohloh/API/Kudos.pm
    version: v1.0.2
  WWW::Ohloh::API::Language:
    file: lib/WWW/Ohloh/API/Language.pm
    version: v1.0.2
  WWW::Ohloh::API::Languages:
    file: lib/WWW/Ohloh/API/Languages.pm
    version: v1.0.2
  WWW::Ohloh::API::Message:
    file: lib/WWW/Ohloh/API/Message.pm
    version: v1.0.2
  WWW::Ohloh::API::Message::Tag:
    file: lib/WWW/Ohloh/API/Message/Tag.pm
    version: v1.0.2
  WWW::Ohloh::API::Messages:
    file: lib/WWW/Ohloh/API/Messages.pm
    version: v1.0.2
  WWW::Ohloh::API::Project:
    file: lib/WWW/Ohloh/API/Project.pm
    version: v1.0.2
  WWW::Ohloh::API::Projects:
    file: lib/WWW/Ohloh/API/Projects.pm
    version: v1.0.2
  WWW::Ohloh::API::Repository:
    file: lib/WWW/Ohloh/API/Repository.pm
    version: v1.0.2
  WWW::Ohloh::API::Role::Fetchable:
    file: lib/WWW/Ohloh/API/Role/Fetchable.pm
    version: v1.0.2
  WWW::Ohloh::API::Role::LoadXML:
    file: lib/WWW/Ohloh/API/Role/LoadXML.pm
    version: v1.0.2
  WWW::Ohloh::API::SizeFact:
    file: lib/WWW/Ohloh/API/SizeFact.pm
    version: v1.0.2
  WWW::Ohloh::API::Stack:
    file: lib/WWW/Ohloh/API/Stack.pm
    version: v1.0.2
  WWW::Ohloh::API::StackEntry:
    file: lib/WWW/Ohloh/API/StackEntry.pm
    version: v1.0.2
requires:
  Carp: '0'
  Date::Parse: '0'
  Digest::MD5: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  Object::InsideOut: '0'
  Params::Validate: '0'
  Readonly: '0'
  Scalar::Util: '0'
  Time::Piece: '0'
  URI: '0'
  XML::LibXML: '0'
  XML::Writer: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/www-ohloh-api/issues
  homepage: https://github.com/yanick/www-ohloh-api
  repository: https://github.com/yanick/www-ohloh-api.git
version: 1.0.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Alexandr Ciornii <chorny@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.ca>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
  - 'Yuval Kogman <nothingmuch@woobling.org>'
x_deprecated: 1
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
